# Generated by Django 5.2.16 on 2026-07-29 14:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DataPendukung',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nim', models.CharField(max_length=20, unique=True, verbose_name='NIM')),
                ('judul_skripsi', models.TextField(blank=True, verbose_name='Judul Skripsi/TA')),
                ('no_ijazah', models.CharField(blank=True, max_length=100, verbose_name='No. Ijazah')),
                ('nama_dekan', models.CharField(blank=True, help_text='Kosongkan untuk pakai default dari config', max_length=200, verbose_name='Nama Dekan')),
            ],
            options={
                'verbose_name': 'Data Pendukung',
                'verbose_name_plural': 'Data Pendukung',
                'ordering': ['nim'],
            },
        ),
        migrations.CreateModel(
            name='Kurikulum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jenjang', models.CharField(choices=[('D3', 'D3'), ('S1', 'S1')], max_length=5, verbose_name='Jenjang')),
                ('angkatan', models.IntegerField(verbose_name='Angkatan (Tahun)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Kurikulum',
                'verbose_name_plural': 'Kurikulum',
                'ordering': ['-angkatan', 'jenjang'],
            },
        ),
        migrations.CreateModel(
            name='PredikatKelulusan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tahun_lulus_mulai', models.IntegerField(verbose_name='Tahun Lulus Mulai')),
                ('tahun_lulus_selesai', models.IntegerField(blank=True, help_text='Kosongkan jika berlaku seterusnya', null=True, verbose_name='Tahun Lulus Selesai')),
                ('ipk_min', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='IPK Minimum')),
                ('ipk_max', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='IPK Maksimum')),
                ('predikat', models.CharField(max_length=100, verbose_name='Predikat Kelulusan')),
            ],
            options={
                'verbose_name': 'Predikat Kelulusan',
                'verbose_name_plural': 'Predikat Kelulusan',
                'ordering': ['-tahun_lulus_mulai', '-ipk_min'],
            },
        ),
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=200, verbose_name='Nama Template')),
                ('file_excel', models.FileField(upload_to='templates/', verbose_name='File Excel Template')),
                ('total_mk', models.IntegerField(help_text='Misal: 34, 50, 51, 55', verbose_name='Total Kapasitas MK')),
                ('baris_halaman_depan', models.IntegerField(help_text='MK sisanya otomatis masuk halaman 2', verbose_name='Jumlah Baris MK Halaman 1')),
                ('cell_mapping', models.JSONField(blank=True, default=dict, help_text='Koordinat cell untuk field: nama, nim, prodi, tempat_lahir, tgl_lahir, dst. Contoh: {"nama": "B5", "nim": "B6", "tabel_mulai_baris": 10, "tabel_kolom": {"no": "A", "kode": "B", "nama": "C", "sks": "D", "nilai": "E", "lambang": "F", "mutu": "G"}, "total_sks": "D50", "ipk": "G50", "predikat": "B52", "judul_skripsi": "B53", "no_ijazah": "B54", "ttd_dekan": "B58"}', verbose_name='Cell Mapping (JSON)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Template',
                'verbose_name_plural': 'Templates',
                'ordering': ['nama'],
            },
        ),
        migrations.CreateModel(
            name='MataKuliahKurikulum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode_mk', models.CharField(max_length=50, verbose_name='Kode MK')),
                ('nama_mk', models.CharField(max_length=300, verbose_name='Nama Mata Kuliah')),
                ('sks', models.IntegerField(verbose_name='SKS')),
                ('urutan_alfabet', models.IntegerField(default=0, verbose_name='Urutan Alfabetis')),
                ('kurikulum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matakuliah', to='core.kurikulum', verbose_name='Kurikulum')),
            ],
            options={
                'verbose_name': 'Mata Kuliah Kurikulum',
                'verbose_name_plural': 'Mata Kuliah Kurikulum',
                'ordering': ['urutan_alfabet'],
            },
        ),
        migrations.CreateModel(
            name='RiwayatGenerate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nim', models.CharField(max_length=20, verbose_name='NIM')),
                ('nama_mahasiswa', models.CharField(blank=True, max_length=300, verbose_name='Nama Mahasiswa')),
                ('jenjang', models.CharField(blank=True, max_length=5, verbose_name='Jenjang')),
                ('angkatan', models.IntegerField(blank=True, null=True, verbose_name='Angkatan')),
                ('mode', models.CharField(choices=[('single', 'Single'), ('batch', 'Batch')], max_length=10, verbose_name='Mode Generate')),
                ('jumlah_mk_retake', models.IntegerField(default=0, verbose_name='Jumlah MK Retake')),
                ('jumlah_mk_kosong', models.IntegerField(default=0, verbose_name='Jumlah MK Kosong')),
                ('jumlah_mk_tidak_dikenali', models.IntegerField(default=0, verbose_name='Jumlah MK Tidak Dikenali')),
                ('status', models.CharField(choices=[('success', 'Berhasil'), ('error', 'Error')], max_length=10, verbose_name='Status')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='Pesan Error')),
                ('generated_at', models.DateTimeField(auto_now_add=True, verbose_name='Waktu Generate')),
                ('generated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Di-generate oleh')),
            ],
            options={
                'verbose_name': 'Riwayat Generate',
                'verbose_name_plural': 'Riwayat Generate',
                'ordering': ['-generated_at'],
            },
        ),
        migrations.AddField(
            model_name='kurikulum',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.template', verbose_name='Template Excel'),
        ),
        migrations.AlterUniqueTogether(
            name='kurikulum',
            unique_together={('jenjang', 'angkatan')},
        ),
    ]
